In [1]:
import numpy as np


In [1]:
a=np.array([2,8,7,4])

NameError: name 'np' is not defined

In [15]:
a[3]

4

In [16]:
np.empty(8)

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 6.95644429e-321, 1.20953760e-312, 7.23168526e-308])

In [17]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.arange(4)

array([0, 1, 2, 3])

In [69]:
x=np.arange(5,9)
x.resize(2,2)
x

array([[5, 6],
       [7, 8]])

In [22]:
np.arange(4,10,2) ## work in the specific interval

array([4, 6, 8])

In [35]:
x=np.linspace(1,5,9 ,dtype=int) 

x#convart it into eqal parts 

array([1, 1, 2, 2, 3, 3, 4, 4, 5])

In [37]:
a=np.array([5,9,7,2,74,8,5])
a

array([ 5,  9,  7,  2, 74,  8,  5])

In [41]:
a.sort() #sort the fuction
a

array([ 2,  5,  5,  7,  8,  9, 74])

In [43]:
x=np.arange(1,9)
y=np.arange(1,12)

In [46]:
c=np.concatenate((x,y)) #  concatenate 
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11])

In [51]:
# 2Dimntionl
x=np.array([[1,2,6,4],[1,5,2,6]])

In [72]:
a=np.arange(1,7)
a.resize(2,3)
print(a)
b=np.arange(6,13)
b.resize(2,3)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 6  7  8]
 [ 9 10 11]]


In [75]:
np.concatenate((a,b),axis=1)# arrange in axis

array([[ 1,  2,  3,  6,  7,  8],
       [ 4,  5,  6,  9, 10, 11]])

In [95]:
a=np.array([[1,2,3],[3,5,3],
          [1,3,5]])

In [99]:
a
# a.size
# type(a)

array([[1, 2, 3],
       [3, 5, 3],
       [1, 3, 5]])

In [101]:
a=np.arange(1,9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [107]:
b=a[np.newaxis,:] # convert to 2d 1row 8 colm
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [109]:
b=a[:,np.newaxis] # convert to 2d 1col 8row
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])